import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/navbar/Navbar";
import FilterBar from "./_components/filters/FilterBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Find My Rooms",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <FilterBar />
        <div className="content">
        {children}
        </div>
        
      </body>
    </html>
  );
}
